import Head from 'next/head';
import React from 'react';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';

function Projects() {
  return (
    <>
      <Head>
        <title>Mikhael | Projects page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Container maxWidth="xl">
            <h1>Projects</h1>
          </Container>
        </Box>
      </main>
    </>
  );
}
export default Projects;
