import Head from 'next/head';
import React from 'react';

function Projects() {
  return (
    <>
      <Head>
        <title>Mikhael | Projects page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Projects</h1>
    </>
  );
}
export default Projects;
