import Head from 'next/head';
import Box from '@mui/material/Box';
import Container from '@mui/material/Container';
import Hero from '@/components/Hero';

export default function Home() {
  return (
    <>
      <Head>
        <title>Mikhael | Home page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Box>
          <Container maxWidth="xl">
            <Hero />
          </Container>
        </Box>
      </main>
    </>
  );
}
